library(readxl)
library(car)
library(MASS)
PK1<-Toyoto[,-c((1:2),(5:6),8,(10:12),15,(19:38))]
pairs(PK1)
cor(PK1)
`mode<-lm(price~.,data=PK1)
summary(mode)
vif(mode)
stepAIC(mode)
mode1<-lm(price~.,Age_08_04+KM+HP+CC+Doors+Gears +Quarterly_Tax+Weight.,data=PK1)
summary(mode1)
vif(mode1)
stepAIC(mode1)
plot(mode1)
residualPlot(mode1)
qqplot(mode1)
avPlot(mode1)
PK1<-PK1[-c,(222),]
mode2<-lm(price~.,Age_08_04+KM+HP+CC+Gears+Quarterly_Tax+Weight.,data = PK1)
summary(mode2)
vif(mode2)
stepAIC(mode2)
plot(mode2)
residualPlot(mode2)
qqplot(mode2)
avPlot(mode2)
influenceIndexPlot(mode2)
PK1<-PK1[-c,(960),]
mode3<-lm(price~.,Age_08_04+KM+HP+CC+Gears+Quarterly_TAX+Weight.,data=PK1)
summary(mode3)
vif(mode3)
stepAIC(mode3)
plot(mode3)
residualPlot(mode3)
qq.plot(mode3)
avPlot((mode3)
qqplot(mode3)       
influenceIndexPlot(mode3)
PK1<-PK1[-c,(620),]
mode4<-lm(price~.,Age_08_04+Km+HP+CC+Gears+Quarterly_TAX+Weight.,data=PK1)
summary(mode4)
Age<- readline(prompt = )
age<-as(integer(Age))
km<-readline(prompt = )
km<-as(integer(km))
hp<-readline(prompt = )
hp<-as(integer(hp))
cc<-readline(prompt = )
cc<-as.integer(cc)
Quarterly tax<-readline(prompt = )
quarterly tax<-as,integer(Quarterly tax)
weight<-readline(prompt = )
weight(as.integer(weight))
Predicted_Price<-predict(mod4,newdata=data.frame(Age_08_04=Age,KM=KM,HP=HP,CC=cc,Gears=Gear,Quarterly_Tax=QT,Weight=Weight))
Predictions<-predict(mod4)
Errors<-data.frame(PK1,'Predictions'=Predictions,'Errors'=PK1$Price-Predictions)

